#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:14.17.0

pipelines:
  branches:
    dev_0.1:
      - step:
          trigger: automatic
          caches:
            - node
          script: # Modify the commands below to build your repository.
          - npm install
          - npm install -g sonarqube-scanner
          - sonar-scanner
            -Dsonar.projectKey=spectra-admin-panel-dev-0.1
            -Dsonar.sources=. 
            -Dsonar.host.url=https://sonarqube.affle.com
            -Dsonar.login=d22d3bbd8c9beb2b1755cb90878733f635703b9b