export const IS_LOADING = "IS_LOADING";
export const ADMIN_DATA = "ADMIN_DATA";
export const NOTIFICATION_DATA_BY_ID = "NOTIFICATION:NOTIFICATION_DATA_BY_ID";
export const NOTIFICATIONS_DATA = "NOTIFICATION:NOTIFICATIONS_DATA";
export const NOTIFICATIONS_QUERY = "NOTIFICATIONS:NOTIFICATIONS_QUERY";
export const NOTIFICATION_ANALYTICS = "NOTIFICATIONS:NOTIFICATION_ANALYTICS";
export const NOTIFICATION_LIST_PAGE_INDEX =
  "NOTIFICATIONS:NOTIFICATION_LIST_PAGE_INDEX";
export const NOTIFICATION_STATUS = "NOTIFICATION_STATUS";
export const CATEGORY_DATA = "CATEGORY_DATA";
export const CATEGORY_DATA_BY_ID = "CATEGORY_DATA_BY_ID";
export const CATEGORY_DATA_BY_SEGMENT_ID = "CATEGORY_DATA_BY_SEGMENT_ID";
export const SEGMENT_DATA = "SEGMENT_DATA";
export const SEGMENT_DATA_BY_ID = "SEGMENT_DATA_BY_ID";
export const FAQ_DATA = "FAQ_DATA";
export const FAQ_DATA_BY_ID = "FAQ_DATA_BY_ID";
